name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Copy config files
        run: |
          cp devDocker/hibernate.heroku src/main/resources/hibernate.properties
          cp devDocker/config.heroku src/main/resources/config.properties

      - name: Get version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Run maven
        run: mvn clean install

      - name: Clean jar files
        run: |
          rm -f target/EagleEyeEar-${{ env.RELEASE_VERSION }}.jar
          cp target/EagleEyeEar-${{ env.RELEASE_VERSION }}-jar-with-dependencies.jar target/EagleEyeEar-${{ env.RELEASE_VERSION }}.jar

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: EagleEyeEar-${{ env.RELEASE_VERSION }}
          path: target/EagleEyeEar-${{ env.RELEASE_VERSION }}.jar
          retention-days: 2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: TBD
          draft: false
          prerelease: false

      - name: Upload release artifact
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: target/EagleEyeEar-${{ env.RELEASE_VERSION }}.jar
          asset_name: EagleEyeEar-${{ env.RELEASE_VERSION }}.jar
          asset_content_type: application/x-java-archive