name: Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master

      - name: Get Ear release artifact
        with:
          repo: 'alexandrepasc/EagleEyeEar'
          file: 'EagleEyeEar-*.jar'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Wing release artifact
        with:
          repo: 'alexandrepasc/EagleEyeWing'
          file: 'EagleEyeWing-*.jar'
          token: ${{ secrets.GITHUB_TOKEN }}